from pathlib import Path

configfile: "config/config.yaml"

# shared paths
DATA_PATH = config["meta"]["data_path"]
SAMPLE_SHEET = config["meta"]["sample_sheet"]
MD5_SHEET = config["meta"]["md5_sheet"]
LOCAL_PATH = Path(config["meta"]["local_path"])

LOCAL_SAMPLES = LOCAL_PATH / "samples.csv"
LOCAL_MD5 = LOCAL_PATH / "md5.txt"

include: "rules/metadata.smk"


onstart:
    print("\n--- Analysis started ---\n")

onsuccess:
    print("\n--- Workflow finished! ---\n")

onerror:
    print("\n--- An error occurred! ---\n")


rule all:
    input:
        str(LOCAL_SAMPLES),
        str(LOCAL_MD5)
    default_target: True
