# -------------------------
# python packages
# -------------------------
from pathlib import Path
import csv

# -------------------------
# setting paths
# -------------------------
configfile: "config/config.yaml"

# shared paths
DATA_PATH = config["meta"]["data_path"]
SAMPLE_SHEET = config["meta"]["sample_sheet"]
MD5_SHEET = config["meta"]["md5_sheet"]
LOCAL_PATH = Path(config["meta"]["local_path"])

LOCAL_SAMPLES = LOCAL_PATH / "samples.csv"
LOCAL_MD5 = LOCAL_PATH / "md5.txt"

FASTQ_DIR = LOCAL_PATH / "fastq"
TRIMMED_DIR = LOCAL_PATH / "trimmed"
BAM_DIR = LOCAL_PATH / "bam"
QC_DIR = LOCAL_PATH / "qc"

# -------------------------
# reference paths
# -------------------------
REF_ROOT = Path(config["reference"]["root"])
REF_SOURCE = REF_ROOT / "source"
REF_FASTA = REF_ROOT / "fasta"
REF_BED = REF_ROOT / "bed"
REF_BWA = REF_ROOT / "bwa"

HG38_GZ = REF_SOURCE / "hg38.analysisSet.fa.gz"
BLACKLIST_GZ = REF_SOURCE / "hg38-blacklist.v2.bed.gz"

HG38_FA = REF_FASTA / "hg38.analysisSet.fa"
LAMBDA_RAW_FA = REF_FASTA / "lambda.fa"
PUC19_RAW_FA = REF_FASTA / "pUC19.fa"

LAMBDA_RENAMED_FA = REF_FASTA / "lambda.renamed.fa"
PUC19_RENAMED_FA = REF_FASTA / "pUC19.renamed.fa"

BLACKLIST_BED_GZ = REF_BED / "hg38-blacklist.v2.bed.gz"

COMBINED_FA = REF_FASTA / "hg38_plus_spikeins.fa"
BWA_FA = REF_BWA / "hg38_plus_spikeins.fa"

# -------------------------
# sample parsing via checkpoint
# -------------------------
def get_samples_df():
    ckpt = checkpoints.download_metadata.get()
    samples_file = ckpt.output.samples

    rows = []

    with open(samples_file) as f:
        reader = csv.DictReader(f)
        for row in reader:
            row["Name"] = row["Name"].strip()
            row["R1_file"] = row["R1_file"].strip().lstrip("/")
            row["R2_file"] = row["R2_file"].strip().lstrip("/")
            row["Path"] = row["Path"].strip().rstrip("/")
            rows.append(row)

    return rows


def get_sample_names():
    rows = get_samples_df()
    return [r["Name"] for r in rows]


def get_fastq_r1(sample):
    rows = get_samples_df()
    for r in rows:
        if r["Name"] == sample:
            return f'gs://{r["Path"]}/{r["R1_file"]}'
    raise ValueError(f"Sample {sample} not found")

def get_fastq_r2(sample):
    rows = get_samples_df()
    for r in rows:
        if r["Name"] == sample:
            return f'gs://{r["Path"]}/{r["R2_file"]}'
    raise ValueError(f"Sample {sample} not found")

def all_fastp_outputs(wildcards):
    samples = get_sample_names()
    return (
        expand(str(QC_DIR / "fastp" / "{sample}.fastp.html"), sample=samples)
        + expand(str(QC_DIR / "fastp" / "{sample}.fastp.json"), sample=samples)
    )

# -------------------------
# including rules
# -------------------------
include: "rules/references_combined.smk"
include: "rules/download_samples.smk"
include: "rules/fastp_trimming.smk"

onstart:
    print("\n--- Analysis started ---\n")

onsuccess:
    print("\n--- Workflow finished! ---\n")

onerror:
    print("\n--- An error occurred! ---\n")

# -------------------------
# rule all
# -------------------------
rule all:
    input:
        all_fastp_outputs
    default_target: True
