meta:
  data_path: weiskittel-projects1/radnecrosis/raw_data
  sample_sheet: radnec_test.csv
  md5_sheet: MD5.txt
  local_path: /home/jupyter/data


reference:
  root: resources/reference
  hg38_fasta_gz: https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/analysisSet/hg38.analysisSet.fa.gz
  hg38_blacklist_bed_gz: https://raw.githubusercontent.com/Boyle-Lab/Blacklist/master/lists/hg38-blacklist.v2.bed.gz
  lambda_fasta: "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=nuccore&id=NC_001416.1&rettype=fasta&retmode=text"
  puc19_fasta: "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=nuccore&id=M77789.2&rettype=fasta&retmode=text"  

simulate_reads:
  read_length: 100
  read_number: 10000
